---
# title: "STA457 Final Project"
# author: "Huifeng Wu"
output: 
  pdf_document:
    latex_engine: xelatex
geometry: margin=2.5cm
header-includes:
  \usepackage{booktabs}
  \usepackage{subfig}
  \usepackage{amsmath}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 3)
library(knitr)
library(xts)
library(astsa)
```

\vspace{-5truemm}

<!-- ## Data Description    -->
<!-- ## Data Visualization and Transformation -->
<!-- ## Proposed Models -->
<!-- ## Parameter Estimation -->
<!-- ## Model Diagnostics and Final Model Choice -->
<!-- ## Prediction -->
<!-- ## Spectral analysis -->
<!-- ## Discussion -->
<!-- ## Appendix -->


<!-- ```{r message=FALSE, warning=FALSE, echo=FALSE, fig.align="center", fig.width=5, fig.asp=1, fig.cap="Model results for under 50's", fig.subcap=c("Fitted values", "Trend of random effect", "Posterior samples and quantiles", "Excess death"), fig.ncol=2, fig.nrow=2, out.width=".4\\linewidth",} -->
<!-- data <- read.csv(file = 'NFLX.csv') -->
<!-- price <- data$Adj.Close -->
<!-- dates <- as.Date(data$Date) -->

<!-- # Create a time series -->
<!-- # Num of trade days yearly = 252 -->
<!-- price <- xts(price,  -->
<!--              order.by = dates,  -->
<!--              frequency = 252) -->

<!-- # Visualization -->
<!-- plot.ts(price) -->
<!-- acf(price) -->

<!-- # Transformation -->
<!-- logPrice <- log(price) -->
<!-- diff2 = diff(logPrice, 2) -->
<!-- plot.ts(diff2) -->
<!-- acf2 <- acf2(diff2, max.lag = 50) -->

<!-- ``` -->


<!-- ```{r message=FALSE, warning=FALSE, echo=FALSE, results='hide'} -->
<!-- # moedls -->
<!-- sarima(logPrice,10,2,1) -->
<!-- # sarima(logPrice,3,2,0) -->
<!-- sarima(logPrice,3,2,1) -->

<!-- # model criteron -->
<!-- sarima(logPrice,10,2,1,details = FALSE)$AIC -->
<!-- sarima(logPrice,10,2,1,details = FALSE)$AICc -->
<!-- sarima(logPrice,10,2,1,details = FALSE)$BIC -->

<!-- sarima(logPrice,3,2,1,details = FALSE)$AIC -->
<!-- sarima(logPrice,3,2,1,details = FALSE)$AICc -->
<!-- sarima(logPrice,3,2,1,details = FALSE)$BIC -->
<!-- ``` -->


<!-- ```{r message=FALSE, warning=FALSE, echo=FALSE, fig.align="center", fig.width=5, fig.asp=1, fig.cap="Exploratory data analysis and model diagnostics for Wiscosin vote counts", fig.subcap=c("Pop dens", "Ind", "white", "random", "fitted", "actual"), fig.ncol=3, fig.nrow=2, out.width=".3\\linewidth",} -->
<!-- # Forecasts -->
<!-- forecasts <- sarima.for(logPrice,4,3,2,1) -->
<!-- U = forecasts$pred+1.96*forecasts$se -->
<!-- L = forecasts$pred-1.96*forecasts$se -->
<!-- forecasts$pred -->
<!-- cbind(L,U) -->

<!-- # spectral analyses -->
<!-- price.per = mvspec(na.omit(diff2), log="no") -->
<!-- (P3<−price.per$details[order(price.per$details[, 3],decreasing= TRUE),]) -->
<!-- P3[1,3]; P3[2,3]; P3[3,3] -->
<!-- price.u =2∗P3[1:3,3]/qchisq(.025,2) -->
<!-- price.l =2∗P3[1:3,3]/qchisq(.975,2) -->
<!-- cbind(price.l,price.u) -->

<!-- ``` -->

<!-- ## Conclusion  -->


<!-- \newpage -->
## Appendix
```{r, fig.show='hide', message=FALSE, warning = FALSE,results='hide'}
library(knitr)
library(xts)
library(astsa)

data <- read.csv(file = 'NFLX.csv')
price <- data$Adj.Close
dates <- as.Date(data$Date)

# Create a time series
price <- xts(price, order.by = dates, frequency = 252) # Num of trade days yearly = 252

# Visualization
plot.ts(price); acf(price)

# Transformation
logPrice <- log(price)
diff2 = diff(logPrice, 2); plot.ts(diff2)
acf2 <- acf2(diff2, max.lag = 50)

# moedls
sarima(logPrice,10,2,1)
# sarima(logPrice,3,2,0)
sarima(logPrice,3,2,1)

# model criteron
sarima(logPrice,10,2,1,details = FALSE)$AIC
sarima(logPrice,10,2,1,details = FALSE)$AICc
sarima(logPrice,10,2,1,details = FALSE)$BIC

sarima(logPrice,3,2,1,details = FALSE)$AIC
sarima(logPrice,3,2,1,details = FALSE)$AICc
sarima(logPrice,3,2,1,details = FALSE)$BIC

# Forecasts
forecasts <- sarima.for(logPrice,4,3,2,1)
U = forecasts$pred+1.96*forecasts$se; L = forecasts$pred-1.96*forecasts$se
forecasts$pred
cbind(L,U)

# spectral analyses
price.per = mvspec(na.omit(diff2), log="no")
(P3<−price.per$details[order(price.per$details[, 3],decreasing= TRUE),])
P3[1,3]; P3[2,3]; P3[3,3]
price.u =2∗P3[1:3,3]/qchisq(.025,2); price.l =2∗P3[1:3,3]/qchisq(.975,2)
cbind(price.l,price.u)
```
